version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - './nginx:/etc/nginx/conf.d'
    ports:
      - '80:80'
    links:
        - test1
  
  test1:
    image: test1
    container_name: test1