version: '3'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    volumes:
      - 'nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    links:
        - test1
  
  test1:
    image: test1
    container_name: test1
    depends_on:
      - proxy
    ports:
      - "3000:3000"
    links:
        - proxy